name: Referral
version: 2.2.2
api-version: 1.13
author: Teenaapje
main: Me.Teenaapje.Referral.ReferralCore
description: Referral
softdepend: [PlaceholderAPI]
commands:
   Ref:
      description: /Ref to get more options